name: CI Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25.x' 
          cache: true

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests with Coverage
        env:
          LOG_ENABLED: "true"
          Environment: "development"
        run: go test -v -coverprofile=coverage.txt -coverpkg=./... ./...